import { useState, useEffect, useRef } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Sparkles, Loader2, CheckCircle, AlertTriangle, ArrowLeft, Coins } from 'lucide-react'
import { useAuthStore } from '../store/authStore'
import { useProjectStore } from '../store/projectStore'
import { generateWebsite } from '../utils/aiEngine'
import { MODELS } from '../utils/constants'
import Button from '../components/ui/Button'
import ModelSelector from '../components/generation/ModelSelector'
import BuyCreditsModal from '../components/billing/BuyCreditsModal'

const STEPS = [
  { label: 'Analyzing your request', desc: 'Understanding what you want to build' },
  { label: 'Designing the layout', desc: 'Creating the page structure and style' },
  { label: 'Generating content', desc: 'Writing code and assembling your site' },
  { label: 'Polishing the result', desc: 'Final touches and optimizations' },
]

const QUICK_PROMPTS = [
  { label: 'SaaS Landing Page', prompt: 'A modern SaaS landing page with hero, features, pricing, testimonials, and contact sections. Clean, professional design.' },
  { label: 'Restaurant Site', prompt: 'A beautiful restaurant website with menu showcase, gallery, reservations, and location. Warm colors.' },
  { label: 'Portfolio', prompt: 'A creative portfolio for a designer with project showcase, skills, and contact form.' },
  { label: 'Startup', prompt: 'A tech startup website with hero, team, features, stats, and contact. Bold modern design.' },
  { label: 'E-commerce', prompt: 'An e-commerce storefront with product grid, categories, and newsletter signup.' },
  { label: 'Blog', prompt: 'A clean blog with featured articles, categories, and newsletter subscription.' },
]

export default function GeneratePage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const { user, profile, canAffordGeneration, getCreditBalance, deductCredits, incrementAiGenerations } = useAuthStore()
  const { createProject } = useProjectStore()
  const [prompt, setPrompt] = useState(searchParams.get('prompt') || '')
  const [generating, setGenerating] = useState(false)
  const [currentStep, setCurrentStep] = useState(-1)
  const [error, setError] = useState('')
  const [selectedModel, setSelectedModel] = useState(searchParams.get('model') || 'gemini-2.5-flash-lite')
  const [showBuyModal, setShowBuyModal] = useState(false)
  const generatingRef = useRef(false)
  const autoGeneratedRef = useRef(false)

  useEffect(() => {
    const promptParam = searchParams.get('prompt')
    if (promptParam && !generating && !generatingRef.current && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true
      setPrompt(promptParam)
      const modelParam = searchParams.get('model')
      if (modelParam) setSelectedModel(modelParam)
      const timer = setTimeout(() => handleGenerate(promptParam), 0)
      return () => clearTimeout(timer)
    }
  }, [searchParams])

  const handleGenerate = async (overridePrompt) => {
    const finalPrompt = overridePrompt || prompt
    if (!finalPrompt.trim() || generatingRef.current) return

    const modelConfig = MODELS.find(m => m.id === selectedModel) || MODELS[0]
    if (!canAffordGeneration(modelConfig.credits)) {
      setError(`Insufficient credits. This model costs ${modelConfig.credits} credit(s). Buy more credits to continue.`)
      return
    }

    generatingRef.current = true
    setGenerating(true)
    setError('')
    setCurrentStep(0)

    const stepInterval = setInterval(() => {
      setCurrentStep((prev) => Math.min(prev + 1, STEPS.length - 1))
    }, 2500)

    try {
      const result = await generateWebsite(finalPrompt, '', selectedModel)
      const html = result?.html || ''

      clearInterval(stepInterval)

      if (!html) {
        setError('AI generation did not return valid HTML. Try a more detailed prompt.')
        setGenerating(false)
        generatingRef.current = false
        return
      }

      await deductCredits(modelConfig.credits)

      const project = await createProject(user.uid, { name: prompt.split('.')[0].slice(0, 50) || 'AI Generated Site', generatedHtml: html, prompt })
      if (!project?.id) { setError('Failed to save project'); setGenerating(false); generatingRef.current = false; return }

      await incrementAiGenerations()
      navigate(`/preview/${project.id}?model=${selectedModel}`, { replace: true })
      return
    } catch (err) {
      clearInterval(stepInterval)
      const msg = err.message || ''
      if (msg.includes('Insufficient credits') || msg.includes('credits')) {
        setError(msg)
      } else if (msg.includes('429') || msg.includes('quota') || msg.includes('RESOURCE_EXHAUSTED')) {
        if (msg.includes('prepayment') || msg.includes('prepay') || msg.includes('credits depleted')) {
          setError('Gemini API: prepay credits depleted. Go to https://ai.studio/projects to add funds or switch to pay-as-you-go.')
        } else {
          setError('Gemini API quota exceeded. Enable billing at https://ai.google.dev/pricing or wait a minute and try again.')
        }
      } else {
        setError(msg || 'Generation failed. Please try again.')
      }
    }
    setGenerating(false)
    generatingRef.current = false
  }

  const handleQuickGenerate = (itemPrompt) => {
    setPrompt(itemPrompt)
  }

  const balance = getCreditBalance()
  const selectedModelConfig = MODELS.find(m => m.id === selectedModel) || MODELS[0]

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="flex items-center justify-between mb-8">
          <button onClick={() => navigate(-1)} className="text-gray-500 hover:text-gray-700 text-sm flex items-center gap-1 transition-colors">
            <ArrowLeft size={16} /> Back
          </button>
          <h1 className="text-lg font-semibold text-gray-900">WebForge AI</h1>
          <button onClick={() => setShowBuyModal(true)} className="flex items-center gap-1.5 px-2.5 py-1.5 bg-indigo-50 hover:bg-indigo-100 border border-indigo-200 rounded-lg text-xs font-medium text-indigo-700 transition-all">
            <Coins size={14} className="text-indigo-500" />
            <span>{balance.total} credits</span>
          </button>
        </div>

        {!generating && (
          <div className="max-w-2xl mx-auto">
            <div className="text-center mb-10">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-600 mb-6 shadow-lg">
                <Sparkles size={32} className="text-white" />
              </div>
              <h2 className="text-3xl font-bold text-gray-900 mb-3">What do you want to build?</h2>
              <p className="text-gray-500 text-lg">Describe your website and AI will generate it in seconds</p>
            </div>

            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <ModelSelector selected={selectedModel} onSelect={setSelectedModel} disabled={generating} />
              </div>
              <span className="text-xs text-gray-400">
                Costs <strong>{selectedModelConfig.credits}</strong> credit{selectedModelConfig.credits > 1 ? 's' : ''}
              </span>
            </div>

            <div className="relative">
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g. A modern SaaS landing page for a project management tool with pricing, features, and a contact form..."
                className="w-full h-36 bg-white border border-gray-200 rounded-xl p-5 text-gray-900 placeholder-gray-400 focus:outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 resize-none text-base shadow-sm"
                onKeyDown={(e) => e.key === 'Enter' && (e.metaKey || e.ctrlKey) && handleGenerate()}
                maxLength={2000}
              />
              <div className="absolute bottom-4 right-4 text-xs text-gray-400">
                {prompt.length}/2000 &middot; Ctrl+Enter
              </div>
            </div>

            <Button onClick={handleGenerate} disabled={!prompt.trim() || generating} className="w-full mt-4 py-3 text-base shadow-sm">
              <Sparkles size={18} className="mr-2" />
              Generate Website ({selectedModelConfig.credits} credit{selectedModelConfig.credits > 1 ? 's' : ''})
            </Button>

            {error && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl">
                <div className="flex items-start gap-2">
                  <AlertTriangle size={16} className="text-red-500 mt-0.5 flex-shrink-0" />
                  <p className="text-red-700 text-sm">{error}</p>
                </div>
                <button onClick={() => setError('')} className="mt-2 text-xs text-red-500 hover:text-red-700 underline">Dismiss</button>
              </div>
            )}

            <div className="mt-10">
              <p className="text-sm text-gray-400 mb-4 text-center">Quick start ideas</p>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {QUICK_PROMPTS.map((item) => (
                  <button
                    key={item.label}
                    onClick={() => handleQuickGenerate(item.prompt)}
                    className="p-3 bg-white border border-gray-200 rounded-xl hover:border-indigo-300 hover:shadow-sm transition-all text-left"
                  >
                    <span className="text-sm font-medium text-gray-800 block">{item.label}</span>
                    <span className="text-xs text-gray-400 mt-1 block line-clamp-2">{item.prompt.slice(0, 80)}...</span>
                  </button>
                ))}
              </div>
            </div>

            <div className="mt-12 text-center">
              <p className="text-xs text-gray-400">Powered by Gemini 2.5 Flash Lite &middot; {balance.total} credits remaining</p>
            </div>
          </div>
        )}

        {generating && (
          <div className="max-w-lg mx-auto pt-12">
            <div className="text-center mb-10">
              <div className="relative inline-flex mb-6">
                <div className="w-20 h-20 rounded-full bg-indigo-100 flex items-center justify-center mx-auto">
                  <Loader2 size={40} className="text-indigo-600 animate-spin" />
                </div>
              </div>
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Building your website</h2>
              <p className="text-gray-500 text-sm">This usually takes 10–15 seconds</p>
            </div>

            <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 space-y-5">
              {STEPS.map((step, i) => {
                const done = i < currentStep
                const active = i === currentStep
                return (
                  <div key={step.label} className="flex items-start gap-4">
                    <div className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium transition-all ${
                      done ? 'bg-green-100 text-green-600' :
                      active ? 'bg-indigo-100 text-indigo-600 ring-2 ring-indigo-200' :
                      'bg-gray-100 text-gray-400'
                    }`}>
                      {done ? <CheckCircle size={16} /> : active ? <Loader2 size={14} className="animate-spin" /> : i + 1}
                    </div>
                    <div className="flex-1 min-w-0 pt-1">
                      <p className={`text-sm font-medium ${done ? 'text-green-700' : active ? 'text-indigo-700' : 'text-gray-400'}`}>
                        {step.label}
                      </p>
                      <p className={`text-xs mt-0.5 ${done ? 'text-green-500' : active ? 'text-indigo-400' : 'text-gray-300'}`}>
                        {step.desc}
                      </p>
                    </div>
                    {active && (
                      <div className="flex-shrink-0 w-20 h-1.5 bg-gray-100 rounded-full overflow-hidden mt-3">
                        <div className="h-full bg-indigo-500 rounded-full animate-pulse" style={{ width: '60%' }} />
                      </div>
                    )}
                    {done && (
                      <div className="flex-shrink-0 w-20 h-1.5 bg-gray-100 rounded-full overflow-hidden mt-3">
                        <div className="h-full w-full bg-green-500 rounded-full" />
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </div>
        )}
      </div>
      <BuyCreditsModal isOpen={showBuyModal} onClose={() => setShowBuyModal(false)} />
    </div>
  )
}
