export const TEMPLATES = [
  {
    id: 'startup',
    name: 'Startup',
    category: 'Business',
    description: 'Modern startup landing page',
    thumbnail: '',
    sections: ['hero', 'features', 'services', 'testimonials', 'pricing', 'contact', 'footer'],
    theme: {
      primaryColor: '#4F46E5',
      secondaryColor: '#7C3AED',
      fontFamily: 'Inter',
      borderRadius: '8px',
    },
  },
  {
    id: 'saas',
    name: 'SaaS Product',
    category: 'Business',
    description: 'Software as a service product page',
    thumbnail: '',
    sections: ['hero', 'features', 'stats', 'pricing', 'faq', 'contact', 'footer'],
    theme: {
      primaryColor: '#0891B2',
      secondaryColor: '#06B6D4',
      fontFamily: 'Inter',
      borderRadius: '12px',
    },
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    category: 'Personal',
    description: 'Creative portfolio for artists & designers',
    thumbnail: '',
    sections: ['hero', 'services', 'gallery', 'testimonials', 'contact', 'footer'],
    theme: {
      primaryColor: '#EC4899',
      secondaryColor: '#F43F5E',
      fontFamily: 'Inter',
      borderRadius: '4px',
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    category: 'Local Business',
    description: 'Restaurant & cafe website',
    thumbnail: '',
    sections: ['hero', 'features', 'gallery', 'testimonials', 'contact', 'footer'],
    theme: {
      primaryColor: '#DC2626',
      secondaryColor: '#F97316',
      fontFamily: 'Inter',
      borderRadius: '8px',
    },
  },
  {
    id: 'consulting',
    name: 'Consulting',
    category: 'Business',
    description: 'Professional consulting firm',
    thumbnail: '',
    sections: ['hero', 'services', 'team', 'testimonials', 'stats', 'contact', 'footer'],
    theme: {
      primaryColor: '#1E40AF',
      secondaryColor: '#2563EB',
      fontFamily: 'Inter',
      borderRadius: '4px',
    },
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce',
    category: 'Business',
    description: 'Online store front page',
    thumbnail: '',
    sections: ['hero', 'features', 'gallery', 'testimonials', 'cta', 'footer'],
    theme: {
      primaryColor: '#059669',
      secondaryColor: '#10B981',
      fontFamily: 'Inter',
      borderRadius: '8px',
    },
  },
  {
    id: 'agency',
    name: 'Creative Agency',
    category: 'Business',
    description: 'Digital agency showcase',
    thumbnail: '',
    sections: ['hero', 'services', 'team', 'gallery', 'testimonials', 'contact', 'footer'],
    theme: {
      primaryColor: '#6D28D9',
      secondaryColor: '#8B5CF6',
      fontFamily: 'Inter',
      borderRadius: '12px',
    },
  },
  {
    id: 'blog',
    name: 'Blog / Magazine',
    category: 'Content',
    description: 'Content publisher & blog',
    thumbnail: '',
    sections: ['hero', 'features', 'cta', 'footer'],
    theme: {
      primaryColor: '#78716C',
      secondaryColor: '#A8A29E',
      fontFamily: 'Inter',
      borderRadius: '4px',
    },
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'Business', label: 'Business' },
  { id: 'Personal', label: 'Personal' },
  { id: 'Local Business', label: 'Local Business' },
  { id: 'Content', label: 'Content' },
]
